import { describe, it, expect, afterAll } from "vitest";
import { createClient } from "@supabase/supabase-js";
import { NextRequest } from "next/server";
import { POST } from "@/app/api/ingest/route";
import { supabaseAdmin } from "@/lib/supabase/admin";
import { computeAndPersistRiskScore } from "@/lib/risk/compute";
import { deleteReadingByTimestamp } from "./helpers/cleanup";

const DEVICE_ID = "nb-001";
const VALID_KEY = process.env.DEVICE_API_KEY!;
const THROWAWAY_DEVICE_ID = "throwaway-risk-scores-realtime-test-device";
const THROWAWAY_API_KEY = "throwaway-key-not-used-for-auth";

const anonClient = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

/**
 * Opens a postgres_changes INSERT subscription on risk_scores and resolves
 * once Supabase confirms SUBSCRIBED — same race-condition guard as
 * tests/realtime.subscribe.test.ts (firing the write before this ack is a
 * race that silently drops the event, since the channel isn't listening
 * yet).
 *
 * Unlike the readings analog's deviceId+timestamp double filter, risk_scores
 * carries no raw timestamp column (D-19). For a POST-triggered insert the
 * real reading_id is only knowable once the request has completed (it's
 * generated by the readings insert inside the route handler), so every
 * received event is buffered by reading_id as it arrives. waitForReadingId()
 * can then be called AFTER the caller learns the real id, checking the
 * buffer first before waiting on a future event — matching reading_id
 * exactly even under concurrent risk_scores INSERTs from other test files
 * running in parallel.
 */
function openRiskScoreSubscription(): Promise<{
  waitForReadingId: (
    readingId: number,
    timeoutMs: number
  ) => Promise<Record<string, unknown> | null>;
  close: () => void;
}> {
  return new Promise((resolveSubscribed, rejectSubscribed) => {
    const received: Record<string, unknown>[] = [];
    const waiters = new Map<number, (row: Record<string, unknown> | null) => void>();

    const channel = anonClient
      .channel(`risk-scores-test-${Date.now()}-${Math.random().toString(36).slice(2)}`)
      .on(
        "postgres_changes",
        { event: "INSERT", schema: "public", table: "risk_scores" },
        (payload) => {
          const row = payload.new as Record<string, unknown>;
          received.push(row);
          const readingId = row.reading_id as number;
          const waiter = waiters.get(readingId);
          if (waiter) {
            waiter(row);
            waiters.delete(readingId);
          }
        }
      )
      .subscribe((status, err) => {
        if (status === "SUBSCRIBED") {
          resolveSubscribed({
            waitForReadingId: (readingId: number, timeoutMs: number) =>
              new Promise((resolve) => {
                const existing = received.find((row) => row.reading_id === readingId);
                if (existing) {
                  resolve(existing);
                  return;
                }
                waiters.set(readingId, resolve);
                setTimeout(() => {
                  if (waiters.has(readingId)) {
                    waiters.delete(readingId);
                    resolve(null);
                  }
                }, timeoutMs);
              }),
            close: () => channel.unsubscribe(),
          });
        } else if (status === "CHANNEL_ERROR" || status === "TIMED_OUT") {
          rejectSubscribed(err ?? new Error(`Realtime subscribe failed: ${status}`));
        }
      });
  });
}

describe("Supabase Realtime — risk_scores anon subscriber (D-20, D-21, RISK-02, STOR-02)", () => {
  const insertedTimestamps: number[] = [];

  afterAll(async () => {
    while (insertedTimestamps.length) {
      const ts = insertedTimestamps.pop()!;
      await deleteReadingByTimestamp(ts); // cascades to risk_scores (ON DELETE CASCADE)
    }
    await supabaseAdmin.from("devices").delete().eq("device_id", THROWAWAY_DEVICE_ID);
  });

  it(
    "delivers a risk_scores INSERT for an nb-001 reading scored via POST /api/ingest, with correctly-cased camelCase keys",
    async () => {
      const timestamp = Date.now() + 600;
      insertedTimestamps.push(timestamp);

      const sub = await openRiskScoreSubscription();

      const res = await POST(
        new NextRequest("http://localhost/api/ingest", {
          method: "POST",
          headers: { "content-type": "application/json", "x-api-key": VALID_KEY },
          body: JSON.stringify({
            deviceId: DEVICE_ID,
            timestamp,
            vitals: { heartRate: 132, spo2: 97, temperature: 36.9, activityScore: 4 },
          }),
        })
      );
      expect(res.status).toBe(201);

      const { data: reading, error: readingError } = await supabaseAdmin
        .from("readings")
        .select("id")
        .eq("deviceId", DEVICE_ID)
        .eq("timestamp", timestamp)
        .maybeSingle();

      expect(readingError).toBeNull();
      expect(reading).not.toBeNull();

      const row = await sub.waitForReadingId(reading!.id, 10000);
      sub.close();

      expect(row).not.toBeNull();
      expect(row).toMatchObject({
        reading_id: reading!.id,
        deviceId: DEVICE_ID,
      });
      expect(["green", "amber", "red"]).toContain(row!.status);
      // Explicitly prove no lowercase-folded key names leaked through
      // (mirrors the readings analog's Pitfall-1 check).
      expect(Object.prototype.hasOwnProperty.call(row!, "deviceid")).toBe(false);
      expect(Object.prototype.hasOwnProperty.call(row!, "readingid")).toBe(false);
    },
    15000
  );

  it(
    "does NOT deliver a risk_scores INSERT for a different, non-nb-001 device's reading (RLS boundary, mirrors Phase 1's T-1-02)",
    async () => {
      await supabaseAdmin
        .from("devices")
        .upsert({ device_id: THROWAWAY_DEVICE_ID, api_key: THROWAWAY_API_KEY });

      const timestamp = Date.now() + 601;
      insertedTimestamps.push(timestamp);

      const { data: throwawayReading, error: insertError } = await supabaseAdmin
        .from("readings")
        .insert({
          deviceId: THROWAWAY_DEVICE_ID,
          timestamp,
          heartRate: 100,
          spo2: 99,
          temperature: 36.5,
          activityScore: 1,
        })
        .select("id, deviceId, timestamp, heartRate, temperature, activityScore")
        .single();

      expect(insertError).toBeNull();
      expect(throwawayReading).not.toBeNull();

      const sub = await openRiskScoreSubscription();

      await computeAndPersistRiskScore(throwawayReading!);

      const row = await sub.waitForReadingId(throwawayReading!.id, 5000);
      sub.close();

      expect(row).toBeNull();
    },
    10000
  );
});
